name: nodejs CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend project
        run: |
          cd frontend
          npm run build

      - name: Install Dependencies
        run: npm install
